// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weilu/wx.proto

package weilu

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	base "github.com/stevenkitter/protorepo/base"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// WXMessage incoimg body message
type WXEncryptedMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WXEncryptedMessage) Reset()         { *m = WXEncryptedMessage{} }
func (m *WXEncryptedMessage) String() string { return proto.CompactTextString(m) }
func (*WXEncryptedMessage) ProtoMessage()    {}
func (*WXEncryptedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cef36836a6a2c6e6, []int{0}
}

func (m *WXEncryptedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WXEncryptedMessage.Unmarshal(m, b)
}
func (m *WXEncryptedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WXEncryptedMessage.Marshal(b, m, deterministic)
}
func (m *WXEncryptedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WXEncryptedMessage.Merge(m, src)
}
func (m *WXEncryptedMessage) XXX_Size() int {
	return xxx_messageInfo_WXEncryptedMessage.Size(m)
}
func (m *WXEncryptedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WXEncryptedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WXEncryptedMessage proto.InternalMessageInfo

func (m *WXEncryptedMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//WXTicketReq save the decrypted message
type WXTicketReq struct {
	AppID                string   `protobuf:"bytes,1,opt,name=appID,proto3" json:"appID,omitempty"`
	InfoType             string   `protobuf:"bytes,2,opt,name=infoType,proto3" json:"infoType,omitempty"`
	Componet             string   `protobuf:"bytes,3,opt,name=componet,proto3" json:"componet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WXTicketReq) Reset()         { *m = WXTicketReq{} }
func (m *WXTicketReq) String() string { return proto.CompactTextString(m) }
func (*WXTicketReq) ProtoMessage()    {}
func (*WXTicketReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cef36836a6a2c6e6, []int{1}
}

func (m *WXTicketReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WXTicketReq.Unmarshal(m, b)
}
func (m *WXTicketReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WXTicketReq.Marshal(b, m, deterministic)
}
func (m *WXTicketReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WXTicketReq.Merge(m, src)
}
func (m *WXTicketReq) XXX_Size() int {
	return xxx_messageInfo_WXTicketReq.Size(m)
}
func (m *WXTicketReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WXTicketReq.DiscardUnknown(m)
}

var xxx_messageInfo_WXTicketReq proto.InternalMessageInfo

func (m *WXTicketReq) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *WXTicketReq) GetInfoType() string {
	if m != nil {
		return m.InfoType
	}
	return ""
}

func (m *WXTicketReq) GetComponet() string {
	if m != nil {
		return m.Componet
	}
	return ""
}

func init() {
	proto.RegisterType((*WXEncryptedMessage)(nil), "weilu.WXEncryptedMessage")
	proto.RegisterType((*WXTicketReq)(nil), "weilu.WXTicketReq")
}

func init() { proto.RegisterFile("weilu/wx.proto", fileDescriptor_cef36836a6a2c6e6) }

var fileDescriptor_cef36836a6a2c6e6 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x99, 0x63, 0xe2, 0x5e, 0x61, 0xca, 0x8b, 0x87, 0xd9, 0x93, 0xec, 0xe0, 0x9f, 0x4b,
	0x23, 0xee, 0x1b, 0xc8, 0x3c, 0x78, 0xd8, 0xa5, 0x0e, 0x5a, 0xf4, 0xd4, 0x66, 0x8f, 0x35, 0xcc,
	0x36, 0x31, 0xc9, 0x3a, 0xf7, 0xed, 0xa5, 0xa9, 0x2b, 0x82, 0x97, 0x90, 0xdf, 0xfb, 0xe4, 0x09,
	0xbf, 0x84, 0x26, 0x3b, 0xa8, 0xcf, 0xad, 0xd8, 0x7d, 0xc7, 0xc6, 0x6a, 0xaf, 0x79, 0x14, 0x38,
	0x3a, 0x2b, 0x72, 0x07, 0xd1, 0x2e, 0xdd, 0x7c, 0x76, 0x4d, 0x9c, 0x66, 0x4f, 0xb5, 0xb4, 0x7b,
	0xe3, 0xb1, 0x5e, 0xc2, 0xb9, 0xbc, 0x04, 0x9f, 0xd3, 0xb0, 0x72, 0xe5, 0x74, 0x70, 0x35, 0xb8,
	0x1d, 0x27, 0xed, 0x76, 0xf6, 0x46, 0xa7, 0x69, 0xb6, 0x52, 0x72, 0x03, 0x9f, 0xe0, 0x8b, 0x2f,
	0x68, 0x94, 0x1b, 0xf3, 0xbc, 0xf8, 0x3d, 0xd2, 0x01, 0x47, 0x74, 0xa2, 0xea, 0x77, 0xbd, 0xda,
	0x1b, 0x4c, 0x8f, 0x42, 0xd0, 0x73, 0x9b, 0x49, 0x5d, 0x19, 0x5d, 0xc3, 0x4f, 0x87, 0x5d, 0x76,
	0xe0, 0x07, 0x4b, 0xe3, 0x34, 0x7b, 0x81, 0x6d, 0x94, 0x04, 0xcf, 0x89, 0x16, 0x08, 0x3e, 0x4b,
	0x57, 0xf2, 0x65, 0x1c, 0xc4, 0xe3, 0xff, 0x92, 0x11, 0xc5, 0xe1, 0x1d, 0x09, 0x9c, 0xe1, 0x7b,
	0x9a, 0x1c, 0xe4, 0x24, 0x54, 0x83, 0x35, 0x73, 0x5f, 0xec, 0xad, 0xff, 0x36, 0x1e, 0xef, 0x5e,
	0x6f, 0x4a, 0xe5, 0x3f, 0xb6, 0x45, 0x2c, 0x75, 0x25, 0x9c, 0x47, 0x83, 0x7a, 0xa3, 0xbc, 0x87,
	0x15, 0xe1, 0x67, 0x2c, 0x8c, 0x16, 0xe1, 0x8a, 0xe2, 0x38, 0x0c, 0xe6, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x99, 0x80, 0x33, 0xe4, 0x54, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WXServiceClient is the client API for WXService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WXServiceClient interface {
	DecryptMsg(ctx context.Context, in *WXEncryptedMessage, opts ...grpc.CallOption) (*base.Resp, error)
	TicketReceived(ctx context.Context, in *WXTicketReq, opts ...grpc.CallOption) (*base.Resp, error)
}

type wXServiceClient struct {
	cc *grpc.ClientConn
}

func NewWXServiceClient(cc *grpc.ClientConn) WXServiceClient {
	return &wXServiceClient{cc}
}

func (c *wXServiceClient) DecryptMsg(ctx context.Context, in *WXEncryptedMessage, opts ...grpc.CallOption) (*base.Resp, error) {
	out := new(base.Resp)
	err := c.cc.Invoke(ctx, "/weilu.WXService/DecryptMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wXServiceClient) TicketReceived(ctx context.Context, in *WXTicketReq, opts ...grpc.CallOption) (*base.Resp, error) {
	out := new(base.Resp)
	err := c.cc.Invoke(ctx, "/weilu.WXService/TicketReceived", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WXServiceServer is the server API for WXService service.
type WXServiceServer interface {
	DecryptMsg(context.Context, *WXEncryptedMessage) (*base.Resp, error)
	TicketReceived(context.Context, *WXTicketReq) (*base.Resp, error)
}

func RegisterWXServiceServer(s *grpc.Server, srv WXServiceServer) {
	s.RegisterService(&_WXService_serviceDesc, srv)
}

func _WXService_DecryptMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WXEncryptedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WXServiceServer).DecryptMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weilu.WXService/DecryptMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WXServiceServer).DecryptMsg(ctx, req.(*WXEncryptedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WXService_TicketReceived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WXTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WXServiceServer).TicketReceived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weilu.WXService/TicketReceived",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WXServiceServer).TicketReceived(ctx, req.(*WXTicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WXService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "weilu.WXService",
	HandlerType: (*WXServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecryptMsg",
			Handler:    _WXService_DecryptMsg_Handler,
		},
		{
			MethodName: "TicketReceived",
			Handler:    _WXService_TicketReceived_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weilu/wx.proto",
}
